blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ General Discussion
    url: https://github.com/nollyscafe/nolly-cli/discussions
    about: "Ask questions, share ideas, or start a discussion!"
